# Generated by Django 4.2.5 on 2023-09-09 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_category_alter_course_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='courses_count',
        ),
        migrations.RemoveField(
            model_name='course',
            name='reviews_count',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students_count',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='courses_count',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='reviews_count',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='students_count',
        ),
    ]
