# Generated by Django 4.2.5 on 2023-09-14 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_cart_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialitem',
            name='section',
        ),
        migrations.AddField(
            model_name='materialitem',
            name='course_content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.coursecontent'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
