# Generated by Django 4.2.5 on 2023-09-14 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_materialitem_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='main', validators=[django.core.validators.FileExtensionValidator(['pdf', 'mp4'])]),
        ),
    ]
