# Generated by Django 4.2.5 on 2023-09-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_materialitem_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='welcome_message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
