# Generated by Django 4.2.5 on 2023-09-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_course_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialitem',
            name='course_content',
        ),
        migrations.AddField(
            model_name='materialitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.course'),
        ),
        migrations.DeleteModel(
            name='CourseContent',
        ),
    ]
