# Generated by Django 4.2.5 on 2023-09-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_materialitem_course_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
