# Generated by Django 4.2.5 on 2023-09-15 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_question_user_question_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sender',
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='main.user'),
        ),
    ]
