# Generated by Django 4.2.5 on 2023-09-15 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_question_receiver_remove_question_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(),
        ),
    ]
